# Ce fichier dit au cluster : "Voici comment aller chercher le secret db-password"
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-db-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # On utilise l'identit√© du robot AKS
    userAssignedIdentityID: "{{ .Values.keyVault.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.keyVault.keyVaultName }}" 
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantId: "{{ .Values.keyVault.tenantId }}"